// Generated by gencpp from file Myrobot/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYROBOT_MESSAGE_ADDTWOINTS_H
#define MYROBOT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <Myrobot/AddTwoIntsRequest.h>
#include <Myrobot/AddTwoIntsResponse.h>


namespace Myrobot
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace Myrobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Myrobot::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::Myrobot::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::Myrobot::AddTwoInts > {
  static const char* value()
  {
    return "Myrobot/AddTwoInts";
  }

  static const char* value(const ::Myrobot::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::Myrobot::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::Myrobot::AddTwoInts > 
template<>
struct MD5Sum< ::Myrobot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Myrobot::AddTwoInts >::value();
  }
  static const char* value(const ::Myrobot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Myrobot::AddTwoIntsRequest> should match 
// service_traits::DataType< ::Myrobot::AddTwoInts > 
template<>
struct DataType< ::Myrobot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::Myrobot::AddTwoInts >::value();
  }
  static const char* value(const ::Myrobot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Myrobot::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::Myrobot::AddTwoInts > 
template<>
struct MD5Sum< ::Myrobot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Myrobot::AddTwoInts >::value();
  }
  static const char* value(const ::Myrobot::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Myrobot::AddTwoIntsResponse> should match 
// service_traits::DataType< ::Myrobot::AddTwoInts > 
template<>
struct DataType< ::Myrobot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::Myrobot::AddTwoInts >::value();
  }
  static const char* value(const ::Myrobot::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYROBOT_MESSAGE_ADDTWOINTS_H
