obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.4
inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /sacn, marking: true, clearing: true, expected_update_rate: 0}
